### ISSUE TITLE
Bot is only betting 1 again

### ISSUE THREAD

**Issue by worldRoa** [FranciscoAT/saltyboy#80] opened 2023-12-05 20:26 UTC
Bot is only betting 1 again, can you reboot it. Also appreciate the effort you put into this bot.

**Comment by FranciscoAT** [comment] 2023-12-05 21:03
Whoops I think I was informed it died a while ago. Should be up and alive
now!

**Comment by worldRoa** [comment] 2023-12-05 22:46
Yep up and running thanks.

**Comment by snakeboy229** [comment] 2023-12-11 18:28
It looks like the bot is down again, its only betting $1, the fighter data on the popout page isnt updating, and it isnt injecting fighter data into the page.

**Comment by FranciscoAT** [comment] 2023-12-11 18:53
Yep looks like the bot died around 6PM UTC yesterday, thanks for the poke!
Should be up and alive now. I have an issue to try and fix the core
problem. But for now, restarting is the best way. I should really update
the extension at the very least to notify users when the upstream REST
resource is out of date so it's a bit more clear 😅

**Comment by snakeboy229** [comment] 2023-12-13 01:01
heya, looks like the bot died again

**Comment by FranciscoAT** [comment] 2023-12-13 02:21
Totally did. Will kick it when I return home in a few. Sorry for the
downtime!

**Comment by necropolis99** [comment] 2023-12-14 20:33
sorry, but i think the bot is down yet again lol.

**Comment by FranciscoAT** [comment] 2023-12-14 20:44
Whew, sockets angry these days.

**Comment by FranciscoAT** [comment] 2024-01-02 16:07
Happy new years! Just checked in on it, seems healthy. Are you still
experiencing issues?

**Comment by Shagzymandias** [comment] 2024-01-02 18:19
Happy New Year! I agree with hiroweeb, though, seems to need a reboot, only betting 1 on red again, no refresh on info.

**Comment by FranciscoAT** [comment] 2024-01-02 19:28
I believe it died in between the messages. Should be working now.

**Comment by hiroweeb** [comment] 2024-01-06 14:58
seems like bot went offline again at around 1am GMT this morning

**Comment by FranciscoAT** [comment] 2024-01-06 15:41
Just checked in, looks to have been working fine. The REST API is
displaying the current ongoing tournament match, Kain Blade v Iron Lantern.

**Comment by hiroweeb** [comment] 2024-01-06 20:37
![image](https://github.com/FranciscoAT/saltyboy/assets/55668771/9a3b9d1f-5ecb-4b63-9ab1-0064a9afb7b0)
Well, don't know if it's an issue on my side then.

**Comment by FranciscoAT** [comment] 2024-01-06 21:46
> ![image](https://private-user-images.githubusercontent.com/55668771/294716632-9a3b9d1f-5ecb-4b63-9ab1-0064a9afb7b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1Nzc4NTcsIm5iZiI6MTcwNDU3NzU1NywicGF0aCI6Ii81NTY2ODc3MS8yOTQ3MTY2MzItOWEzYjlkMWYtNWVjYi00YjYzLTlhYjEtMDA2NGE5YWZiN2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIxNDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlODUxYTA4ZGEwZDM3NTU4YWQ5MmFhMGMzMGJlYzY4MmRkOWZjNWZlZjg3ZmJlNTg0MDI5NDdhODcxMTc2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v3d5IFPQ7pL7fOVjyS4Ffb9Jho6uJPz8zMGb7EX1xbA) Well, don't know if it's an issue on my side then.

Just re-verified that SaltyBoy appeared to be working on my end. Can you try the Verbose Debugging steps explained in this wiki page? https://github.com/FranciscoAT/saltyboy/wiki/HOWTO:-Debugging#verbose-debugging. Should help us gleam if something off is happening on your end.

**Comment by hiroweeb** [comment] 2024-01-06 23:05
I think the extension goes on standby if the url includes arguments.
The cause of the trigger is probably that I kill my browser process just to keep all my tabs open for the next time.
My main SB window had "https://www.saltybet.com/?selectedplayer=player1&wager=1&player1=Physalis_f" and the console would stay mute, so no update. Tried removing the args and it's working now.

**Comment by FranciscoAT** [comment] 2024-01-07 04:45
Ah I was able to replicate the issue. I believe it has to do with the [Manifest](https://github.com/FranciscoAT/saltyboy/blob/master/extension/src/manifest.json#L15) and basically Chrome is refusing to load the extension's content script if there are query parameters in the path. This should hopefully be a rather trivial update.

**Closed** 2024-01-17 14:40 UTC

**Comment by dli9327** [comment] 2024-02-21 22:40
Bot has been betting 1 for me

**Comment by FranciscoAT** [comment] 2024-02-21 22:51
> Bot has been betting 1 for me

Should be alive, doing some local development / updates on SaltyBoy. Causes things to go down when using the same token to connect to the IRC at the same time as the live service. Hopefully, some cool under the hood updates coming down the road. Knock out some of these longstanding issues lol. 

Also next time feel free to use #62, dedicated issue for this sort of notice.
